language: java
jdk:
    - openjdk8
    - openjdk11

cache:
  directories:
  - $HOME/.m2

install:
    - pip install --user prettytable colorama coverage coveralls Sphinx

script:
    - mvn clean install
    - python panc/src/main/scripts/panlint/tests.py
    - coverage run --source=panc/src/main/scripts/panlint --omit panc/src/main/scripts/panlint/tests.py panc/src/main/scripts/panlint/tests.py

after_success: coveralls
